version: '2'

services:
  mysql:
    image: mysql:8.0
    container_name: osticket-mysql
    hostname: mysql
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secretroot
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=secretsql
  
  osticket:
    image: filug/docker-osticket
    container_name: osticket
    hostname: osticket
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3003:80"
      

ENDE YML von filug/docker-osTicket

Then build docker containers via following command

docker-compose up -d

In your web-browser open http://localhost:3003 page and finalize osTicket configuration.

Within Database Settings sectuon please put following values:

MySQL Table Prefix - ost_
MySQL Hostname - mysql

MySQL Database - this same as defined by MYSQL_DATABASE in docker-compose.yml file,
MySQL Username - this same as defined by MYSQL_USER in docker-compose.yml file,
MySQL Password - this same as defined by MYSQL_PASSWORD in docker-compose.yml file.

Post-install
After osTicket setup please delete /var/www/html/setup/ directory as suggested by osTicket warning.